### PR TITLE
Pulled in additions from some forks/patches

### PR DESCRIPTION
**Pull request by joshuafuller**

### CODE REVIEW

**Comment by joshuafuller** [comment]
I pulled in a few patches from forks and tried to consolidate everything into one pull request.
These are additions, no changes to previous files.

**Comment by Clutch152** [comment]
Merged

**Comment by joshuafuller** [comment]
That was fast. Thanks !

**Comment by Clutch152** [comment]
I just hope they work since I can no longer test them myself :(

**Pull request merged**
