### PR TITLE
added mitmproxy technique

### PR DESCRIPTION
**Pull request by fyrue819**

### CODE REVIEW

**Comment by Clutch152** [comment]
Interesting and I could add it to a separate branch or something but these scripts are meant to be structured such that they can be entered in a standard browser so users don't need to download overly complex software.
That being said, there are some who do want to download said software and dive into the technical aspect of things :P

**Comment by fyrue819** [comment]
I eventually want to make it automatic but I have to analyze the network packets that ask for each content in the tabs. I have yet to crack the mitmproxy API yet. Some of the examples help a little.

**Comment by Clutch152** [comment]
ok, just let me know when you are ready for me to do the merge. I will leave this open :)

**Comment by fyrue819** [comment]
A good note to know is that I've only used it on skillport, since it looks like more of a contracted product for service members.

**Comment by fyrue819** [comment]
I'm good for it. I will have picture walkthrough of it eventually. But that will come when I have some time.

**Comment by Clutch152** [comment]
alrighty

**Pull request merged**
